defaults:
  - trainer: hf_sfttrainer
  - env: default
  - _self_

model:
  _target_: transformers.AutoModel.from_pretrained
  pretrained_model_name_or_path: giwone1330/imdb_m_tiny
  trust_remote_code: true

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: giwone1330/imdb_m_tiny
  trust_remote_code: true

dataset:
  _target_: datasets.load_dataset
  path: "imdb"
  non_inst:
    pre_processor:
      _target_: src.data.pre_processor.causal_lm_pre_processor
      map_args:
        batched: true
        batch_size: 1000
        num_proc: max
      manipulate_args:
        prompt: prompt
        completion: completion
      formatter:
        _target_: src.data.pre_processor.formatter
        method_name: format_imdb_for_prompt_completion  # requires new method (see note below)
    split_map:
      train: train
      eval: test  # IMDB uses "test" split, not "eval"

trainer: null

evaluator:
  _target_: src.eval.evaluator.CustomEvaluator
  non_inst:
    metrics:
      sentimentAccuracy:
        _target_: evaluate.load
        path: ./src/metrics/sentiment_accuracy/metric.py
    generate_args:
      max_new_tokens: 3
      num_beams: 1
      do_sample: False
      use_cache: False

env:
  huggingface: null