_target_: transformers.TrainingArguments
output_dir: null
eval_strategy: epoch
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
torch_empty_cache_steps: null
max_grad_norm: 1.0
num_train_epochs: 3
logging_dir: null
logging_first_step: true
logging_steps: 1
logging_nan_inf_filter: true
save_strategy: epoch
save_total_limit: 10
seed: 42
bf16: false
fp16: false
bf16_full_eval: false
fp16_full_eval: false
dataloader_num_workers: 0
run_name: null
remove_unused_columns: true
load_best_model_at_end: true
metric_for_best_model: null
greater_is_better: null
label_smoothing_factor: 0.0
report_to: all
include_for_metrics:
- inputs
- loss
torch_compile: false
eval_on_start: true